services:
  apitemplate.api:
    image: ${DOCKER_REGISTRY-}apitemplateapi
    build:
      context: .
      dockerfile: ApiTemplate.API/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=Template;User ID=sa;Password=1q2w3e4r@#$;Trust Server Certificate=True"
    ports:
      - "8080:8080"
      - "8081:8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - "SA_PASSWORD=1q2w3e4r@#$"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
